In [27]:
import numpy as np
a=np.array([1,2,3,4,5],dtype=np.int32)

# a=np.arange(1,11)
# a = a.astype('int64')
print(a)
np.savetxt('/home/mca/Desktop/TCR22MCA-2005/Cycle -1/file.txt',a,delimiter=",")
x=np.array([[1,2,3],[5,6,7]])
np.savetxt("/home/mca/Desktop/TCR22MCA-2005/Cycle -1/file1.txt",x,fmt="%5d",delimiter=",")
np.savetxt("/home/mca/Desktop/TCR22MCA-2005/Cycle -1/file1.csv",x,delimiter=",")

y=np.loadtxt(open("/home/mca/Desktop/TCR22MCA-2005/Cycle -1/file1.txt","rb"),delimiter=",")
print(y.astype('int64'))
print()
z=np.genfromtxt("/home/mca/Desktop/TCR22MCA-2005/Cycle -1/file1.txt",delimiter=",")
print(z.astype('int64'))

[1 2 3 4 5]
[[1 2 3]
 [5 6 7]]

[[1 2 3]
 [5 6 7]]
