In [1]:
import numpy as np


In [2]:
print(np.__version__)


1.21.5


In [3]:
a=np.array([1,2,3,4])

In [4]:
print(a)

[1 2 3 4]


In [6]:
a.size

4

In [10]:
print(type(a))

<class 'numpy.ndarray'>


In [11]:
a.dtype

dtype('int64')

In [13]:
arr=np.zeros(5)
print(arr)

[0. 0. 0. 0. 0.]


In [27]:
arr=np.ones(5)
print(arr)
arr = arr.astype('int64')
arr.dtype
print(arr)

[1. 1. 1. 1. 1.]
[1 1 1 1 1]


In [24]:
arr.shape

(5,)

In [20]:
arr=np.array([[1,2,3],[1,1,1]])
print(arr)
arr.shape

[[1 2 3]
 [1 1 1]]


(2, 3)

In [30]:
array=np.array([1,2,3,4,5,6,7,8,9])
newarr=array.reshape(3,3) # Element save to new array
print(newarr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [35]:
array=np.array([1,2,3,4,5,6,7,8,9])
array.resize(3,4) # Element changes in same array 
print(array)
print(array.ndim)#number of diamension

[[1 2 3 4]
 [5 6 7 8]
 [9 0 0 0]]
2


In [38]:
arr=np.array([1,2,3,4,5,6,7,8])
print(arr[1:5])
print(arr[1:])
print(arr[:3])
print(arr[-3:-1])
print(arr[::-1])

[2 3 4 5]
[2 3 4 5 6 7 8]
[1 2 3]
[6 7]
[8 7 6 5 4 3 2 1]


In [40]:
x=np.zeros((8,8),dtype=int)
x[1::2,::2]=1
x[::2,1::2]=1
print(x)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [59]:
y=np.zeros((8,8),dtype=int)
y[::2,::2]=1
y[1::2,1::2]=1
print(y)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [62]:
arr1=np.array([1,2,3,4,5,6,7,8,9,9,9,9,9,2,2,2,1,10])
arr2=np.array([1,2,20])
print(np.in1d(arr2,arr1)) # find duplicate element. It returns Boolean

[ True  True False]


In [63]:
print(np.unique(arr1))

[ 1  2  3  4  5  6  7  8  9 10]


In [64]:
print(np.intersect1d(arr1,arr2))#intersection
print(np.union1d(arr1,arr2)) #union

[1 2]
[ 1  2  3  4  5  6  7  8  9 10 20]


In [67]:
mat1=np.arange(9).reshape(3,3) # arange(9) gets element 0-9
print(mat1)
mat2=np.ones((3,3),dtype="int")
print(mat2)
sum=mat1+mat2
print(sum)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [73]:
prod1=np.multiply(mat1,mat2)
prod2=np.matmul(mat1,mat2)
prod3=mat1*mat2
prod4=np.dot(mat1,mat2)
print(prod1)
print(prod2)
print(prod3)
print(prod4)
print("Transpose")
print(np.transpose(mat1))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 3  3  3]
 [12 12 12]
 [21 21 21]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 3  3  3]
 [12 12 12]
 [21 21 21]]
Transpose
[[0 3 6]
 [1 4 7]
 [2 5 8]]


In [75]:
print(np.linalg.det([[1,2],[3,4]]))

-2.0000000000000004


In [76]:
print(np.linalg.inv([[1,2],[3,4]]))

[[-2.   1. ]
 [ 1.5 -0.5]]


In [79]:
m=np.arange(9).reshape(3,3)
w,v = np.linalg.eig(m)
print("Eigenvalue:",w)
print("eigenVector:",v)

Eigenvalue: [ 1.33484692e+01 -1.34846923e+00 -2.48477279e-16]
eigenVector: [[ 0.16476382  0.79969966  0.40824829]
 [ 0.50577448  0.10420579 -0.81649658]
 [ 0.84678513 -0.59128809  0.40824829]]


In [80]:
z=np.array([[1+0.j,2+5.j]])
print(z)
print(z.real)
print(z.imag)

[[1.+0.j 2.+5.j]]
[[1. 2.]]
[[0. 5.]]


In [81]:
z1=np.array([[1,2],[3,4]],dtype="complex")
print(z1)

[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]


In [84]:
c=np.asfarray([1,2,3,4,5,6])
print(c)

[1. 2. 3. 4. 5. 6.]


In [103]:

arr=np.ones((5,5),dtype="int")



print(arr)

[[0 0 1 1 1]
 [0 0 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
