In [1]:
import numpy as np


In [25]:
array1=np.arange(1,16)
print(array1)
print("size ")
print(array1.size)
print("Update its 8th element")
array1[7]=2
print(array1)
print("Reverse the array")
print(array1[::-1])
print("Convert it into 7 x 2 matrix ")
array1.resize(7,2)
print(array1)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
size 
15
Update its 8th element
[ 1  2  3  4  5  6  7  2  9 10 11 12 13 14 15]
Reverse the array
[15 14 13 12 11 10  9  2  7  6  5  4  3  2  1]
Convert it into 7 x 2 matrix 
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  2]
 [ 9 10]
 [11 12]
 [13 14]]


In [26]:
print("ranging from 22 to 42.")
array2=np.arange(22,43)
print(array2)
print("Shape")
print(array2.shape)



ranging from 22 to 42.
[22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42]
Shape
(21,)


[ 1  2  3  4  5  6  7  2  9 10 11 12 13 14 15]


array([15, 14, 13, 12, 11, 10,  9,  2,  7,  6,  5,  4,  3,  2,  1])

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  2]
 [ 9 10]
 [11 12]
 [13 14]]


In [1]:
import numpy as np
arr=np.zeros((8,8),dtype="int")
# print(arr)
arr[::2,::4]=1
arr[::2,1::4]=1
arr[1::2,3::4]=1
arr[1::2,2::4]=1
print(arr)

[[1 1 0 0 1 1 0 0]
 [0 0 1 1 0 0 1 1]
 [1 1 0 0 1 1 0 0]
 [0 0 1 1 0 0 1 1]
 [1 1 0 0 1 1 0 0]
 [0 0 1 1 0 0 1 1]
 [1 1 0 0 1 1 0 0]
 [0 0 1 1 0 0 1 1]]
