In [5]:
import numpy as np
n=np.random.random([3,3])
print(n)

[[0.89729727 0.25183514 0.14213832]
 [0.14731278 0.21453822 0.91808622]
 [0.56980947 0.87263014 0.22480164]]


In [8]:
a=np.array([[0,2,1],[0,1,2]])
U,S,V=np.linalg.svd(a,full_matrices=True)
print(U)
print(S)
print(V)

[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
[3. 1.]
[[ 0.00000000e+00  7.07106781e-01  7.07106781e-01]
 [-5.55111512e-17 -7.07106781e-01  7.07106781e-01]
 [-1.00000000e+00  1.11022302e-16 -5.55111512e-17]]
